
trim_adatpters()
{
	CORES=3
	FILE1_NAME=$1
	FILE2_NAME=$2

	IN_LOCAL_READS_BASE_PATH=$LOCAL_READS_BASE_PATH/raw
	OUT_LOCAL_READS_BASE_PATH=$LOCAL_READS_BASE_PATH/clean1

	ADAPTERS_FILE_PATH=/home/ubuntu/nucleosomes/data/reduced_Sequencing_adaptors.fasta

	# si no seteo el tam minimo -m en 1 quedan reads de long 0
	#cutadapt -j $CORES -m 15 -a file:$ADAPTERS_FILE_PATH -g file:$ADAPTERS_FILE_PATH -o $OUT_LOCAL_READS_BASE_PATH/$FILE1_NAME $IN_LOCAL_READS_BASE_PATH/$FILE1_NAME
	#cutadapt -j $CORES -m 15 -a file:$ADAPTERS_FILE_PATH -g file:$ADAPTERS_FILE_PATH -o $OUT_LOCAL_READS_BASE_PATH/$FILE2_NAME $IN_LOCAL_READS_BASE_PATH/$FILE2_NAME
	cutadapt -j $CORES -m 15 -a file:$ADAPTERS_FILE_PATH -g file:$ADAPTERS_FILE_PATH -A file:$ADAPTERS_FILE_PATH -G file:$ADAPTERS_FILE_PATH -o $OUT_LOCAL_READS_BASE_PATH/$FILE1_NAME -p $OUT_LOCAL_READS_BASE_PATH/$FILE2_NAME $IN_LOCAL_READS_BASE_PATH/$FILE1_NAME $IN_LOCAL_READS_BASE_PATH/$FILE2_NAME

	rm $IN_LOCAL_READS_BASE_PATH/$FILE1_NAME
	rm $IN_LOCAL_READS_BASE_PATH/$FILE2_NAME
}

trim_Gs()
{
	CORES=3
	FILE1_NAME=$1
	FILE2_NAME=$2

	IN_LOCAL_READS_BASE_PATH=$LOCAL_READS_BASE_PATH/clean1
	OUT_LOCAL_READS_BASE_PATH=$LOCAL_READS_BASE_PATH/clean

#	cutadapt -j $CORES -m 15 -a "G{50}" -o $OUT_LOCAL_READS_BASE_PATH/$FILE1_NAME $IN_LOCAL_READS_BASE_PATH/$FILE1_NAME
#	cutadapt -j $CORES -m 15 -a "G{50}" -o $OUT_LOCAL_READS_BASE_PATH/$FILE2_NAME $IN_LOCAL_READS_BASE_PATH/$FILE2_NAME
	cutadapt -j $CORES -m 15 -a "G{50}" -g "G{50}" -A "G{50}" -G "G{50}" -o $OUT_LOCAL_READS_BASE_PATH/$FILE1_NAME -p $OUT_LOCAL_READS_BASE_PATH/$FILE2_NAME $IN_LOCAL_READS_BASE_PATH/$FILE1_NAME $IN_LOCAL_READS_BASE_PATH/$FILE2_NAME

	rm $IN_LOCAL_READS_BASE_PATH/$FILE1_NAME
	rm $IN_LOCAL_READS_BASE_PATH/$FILE2_NAME

}



source activate cutadapt

#files_head="H3_IN_300U_S1_R H3_IP_300U_S5_R IN_neg_2_400U_S4_R IP_neg_2_400U_S8_R Me1_IN_200U_S3_R Me1_IP_200U_S7_R Me2_IN_350U_S2_R Me2_IP_350U_S6_R"
# files_head="H3_IN_300U_S1_R"
# files_head="H3_IP_300U_S5_R"
# files_head="IN_neg_2_400U_S4_R IP_neg_2_400U_S8_R Me1_IN_200U_S3_R Me1_IP_200U_S7_R Me2_IN_350U_S2_R Me2_IP_350U_S6_R"
files_head="CLJ_1_70U_comb_R"

#LOCAL_READS_BASE_PATH=/home/ubuntu/tmp_disk/reads/MNase
LOCAL_READS_BASE_PATH=/home/ubuntu/disco_tmp/reads/MNase
S3_READS_BASE_PATH=s3://tcruzi-nucleosome/MNase/reads
LOCAL_CLEAN_READS_BASE_PATH=$LOCAL_READS_BASE_PATH/clean  
S3_CLEAN_READS_BASE_PATH=$S3_READS_BASE_PATH/clean

for file_head in $files_head; do
    FILE1_NAME=$file_head'1.fastq.gz'
    FILE2_NAME=$file_head'2.fastq.gz'
	echo $FILE1_NAME
	echo $FILE2_NAME

	RAW_LOCAL_READS_BASE_PATH=$LOCAL_READS_BASE_PATH/raw
	RAW_S3_READS_BASE_PATH=$S3_READS_BASE_PATH/raw

	aws s3 cp $RAW_S3_READS_BASE_PATH/$FILE1_NAME $RAW_LOCAL_READS_BASE_PATH
	aws s3 cp $RAW_S3_READS_BASE_PATH/$FILE2_NAME $RAW_LOCAL_READS_BASE_PATH

 	trim_adatpters $FILE1_NAME $FILE2_NAME
	trim_Gs $FILE1_NAME $FILE2_NAME

	aws s3 cp $LOCAL_CLEAN_READS_BASE_PATH/$FILE1_NAME $S3_CLEAN_READS_BASE_PATH/$FILE1_NAME
	aws s3 cp $LOCAL_CLEAN_READS_BASE_PATH/$FILE2_NAME $S3_CLEAN_READS_BASE_PATH/$FILE2_NAME  

	rm $LOCAL_CLEAN_READS_BASE_PATH/$FILE1_NAME
	rm $LOCAL_CLEAN_READS_BASE_PATH/$FILE2_NAME

done

